[package]
name = "iso-dwarf"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
amethyst = "0.10.0"
rand = "0.6.5"
serde = "1.0.90"
libdwarf = { path = "libdwarf" }

[workspace]
members = [
    # Worker/object sim.
    'libdwarf',
    # Terrain/biome generation.
    'libterrain',
]