[package]
name = "stone-cunning"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
rand = "0.6.5"
serde = "1.0.93"
specs-derive = "0.4.0"
# Simulation code
libdwarf = { path = "libdwarf" }
# Terrain generation
libterrain = { path = "libterrain" }

[dependencies.amethyst]
version = "0.11.1"
features = ["metal"]

[workspace]
members = [
    # Worker/object sim.
    'libdwarf',
    # Terrain/biome generation.
    'libterrain',
]

[profile.release]
debug = true
incremental = true