[package]
name = "libdwarf"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"

[dependencies]
ron = "0.5.1"
serde = "1.0.101"
specs = "0.15.1"
specs-derive = "0.4.0"
libterrain = { path = "../libterrain" }

[dev-dependencies]
termion = "1.5.3"