[package]
name = "libterrain"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"

[dependencies]
core = { path = "../core" }
noise = "0.6.0"
rand = "0.7.2"
libpath = { path = "../libpath" }