[package]
name = "libterrain"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = { version = "0.18.1", features = ["serde-serialize", "mint"] }
noise = "0.6.0"
rand = "0.7.2"
libpath = { path = "../libpath" }