[package]
name = "core"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"

[dependencies.amethyst]
version = "0.15.0"
default-features = false
features = ["audio", "metal", "renderer", "no-slow-safety-checks"]
