[package]
name = "libpath"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.18.0"
rand = "0.7.0"
libterrain = { path = "../libterrain" }