[package]
name = "libpath"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = { version = "0.18.1", features = ["serde-serialize", "mint"] }
rand = "0.7.2"
indexmap = "1.2.0"

[dev-dependencies]
libterrain = { path = "../libterrain" }