[package]
name = "libpath"
version = "0.1.0"
authors = ["Andrew Huynh <a5thuynh@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
indexmap = "1.3.0"

[dev-dependencies]
core = { path = "../core" }
libterrain = { path = "../libterrain" }